### ISSUE TITLE
MythicMobs compatibility issue

### ISSUE THREAD

**Issue by LazoYoung** [LazoYoung/CraftGames#58]
This error occurs in MythicMobs plugin's task execution.
I presume this plugin has to remove MythicMob entities before deleting world.

```
[00:34:54 ERROR]: [MythicMobs] [SCHEDULER] Exception thrown whilst executing task
[00:34:54 WARN]: java.lang.NullPointerException
[00:34:54 WARN]:        at io.lumine.xikage.mythicmobs.drops.LootBag.equip(LootBag.java:201)
[00:34:54 WARN]:        at io.lumine.xikage.mythicmobs.mobs.MythicMob.lambda$applyMobOptions$2(MythicMob.java:857)
[00:34:54 WARN]:        at io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToSupplier.get(Delegates.java:95)
[00:34:54 WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:653)
[00:34:54 WARN]:        at io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:71)
[00:34:54 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[00:34:54 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[00:34:54 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[00:34:54 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[00:34:54 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[00:34:54 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
```

**Comment by LazoYoung** [comment]
This error occurs unpredictably. It seems that MythicMobs is solely responsible for this.

**Comment by SamGamerYT** [comment]
```

[19:20:14 ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityShootBowEvent
[19:20:14 WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.mobs.ActiveMob.getType()" because "am" is null
[19:20:14 WARN]:        at MythicMobs-5.0.0-alpha1.jar//io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onShootTrigger(BukkitSkillTriggers.java:556)
[19:20:14 WARN]:        at MythicMobs-5.0.0-alpha1.jar//io.lumine.xikage.mythicmobs.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[19:20:14 WARN]:        at MythicMobs-5.0.0-alpha1.jar//io.lumine.xikage.mythicmobs.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[19:20:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:20:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:20:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[19:20:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:593)
[19:20:14 WARN]:        at net.minecraft.world.entity.monster.EntitySkeletonAbstract.a(EntitySkeletonAbstract.java:186)
[19:20:14 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalBowShoot.e(PathfinderGoalBowShoot.java:128)
[19:20:14 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:53)
[19:20:14 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:154)
[19:20:14 WARN]:        at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:883)
[19:20:14 WARN]:        at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3234)
[19:20:14 WARN]:        at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:662)
[19:20:14 WARN]:        at net.minecraft.world.entity.monster.EntityMonster.movementTick(EntityMonster.java:43)
[19:20:14 WARN]:        at net.minecraft.world.entity.monster.EntitySkeletonAbstract.movementTick(EntitySkeletonAbstract.java:112)
[19:20:14 WARN]:        at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2960)
[19:20:14 WARN]:        at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:424)
[19:20:14 WARN]:        at net.minecraft.world.entity.monster.EntitySkeleton.tick(EntitySkeleton.java:82)
[19:20:14 WARN]:        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1198)
[19:20:14 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:802)
[19:20:14 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
[19:20:14 WARN]:        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:781)
[19:20:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1635)
[19:20:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493)
[19:20:14 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490)
[19:20:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283)
[19:20:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[19:20:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Ljduginski** [comment]
I am also having the same error. 

ERROR20:06:59
[MythicMobs]: [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityShootBowEvent
WARN20:06:59
java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.mobs.ActiveMob.getType()" because "am" is null
at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onShootTrigger(BukkitSkillTriggers.java:556)
at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.events.functional.single.EventListener.execute(EventListener.java:131)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:584)
at net.minecraft.world.entity.monster.EntitySkeletonAbstract.a(EntitySkeletonAbstract.java:205)
at net.minecraft.world.entity.ai.goal.PathfinderGoalBowShoot.e(PathfinderGoalBowShoot.java:128)
at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:53)
at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:151)
at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:844)
at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3156)
at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:625)
at net.minecraft.world.entity.monster.EntityMonster.movementTick(EntityMonster.java:43)
at net.minecraft.world.entity.monster.EntitySkeletonAbstract.movementTick(EntitySkeletonAbstract.java:130)
at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2882)
at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:393)
at net.minecraft.world.entity.monster.EntitySkeleton.tick(EntitySkeleton.java:65)
at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1114)
at net.minecraft.world.level.World.a(World.java:986)
at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:775)
at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by terrible-gh** [comment]
[MythicMobs] [SCHEDULER] Exception thrown whilst executing task

**Comment by LazoYoung** [comment]
@Oraklx @SamGamerYT My project has nothing to do with your issue. Direct your inquiries to the author of MythicMobs.
