### ISSUE TITLE
MythicMobs / MMOItems Incompability

### ISSUE THREAD

**Issue by LOCNetwork** [LazoYoung/CraftGames#92]
[MythicMobs] [EVENTS] Exception thrown whilst handling event: io.lumine.xikage.mythicmobs.api.bukkit.events.MythicDropLoadEvent
[12:55:42 WARN]: java.lang.NoSuchMethodError: net.Indyuce.mmoitems.manager.TypeManager.has(Ljava/lang/String;)Z
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.compatibility.MMOItemsSupport$MMOItemsDrop.<init>(MMOItemsSupport.java:75)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.compatibility.MMOItemsSupport.lambda$load$0(MMOItemsSupport.java:44)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[12:55:42 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:55:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:55:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.drops.droppables.CustomDrop.lambda$new$0(CustomDrop.java:35)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[12:55:42 WARN]:        at io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[12:55:42 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:55:42 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[12:55:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[12:55:42 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:55:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:55:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:55:42 WARN]:        at java.lang.Thread.run(Thread.java:748)

This is happening after updating the MythicMobs version

**Comment by LazoYoung** [comment]
Could you send me your game script and the installed version of CraftGames so that I can seek the problem?

**Comment by LazoYoung** [comment]
I'm closing this thread as I got no reply for weeks. If you need further assist, you may open up another issue.
