### ISSUE TITLE
EntityShootBowEvent Spam in console 

### ISSUE THREAD

**Issue by Ljduginski** [LazoYoung/CraftGames#94]
It doesn't happen very often but I don't know how to fix it.  I don't know what "because "am" is null" means.

`ERROR20:06:59
[MythicMobs]: [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityShootBowEvent
WARN20:06:59
java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.mobs.ActiveMob.getType()" because "am" is null
at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onShootTrigger(BukkitSkillTriggers.java:556)
at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.events.functional.single.EventListener.execute(EventListener.java:131)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:584)
at net.minecraft.world.entity.monster.EntitySkeletonAbstract.a(EntitySkeletonAbstract.java:205)
at net.minecraft.world.entity.ai.goal.PathfinderGoalBowShoot.e(PathfinderGoalBowShoot.java:128)
at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:53)
at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:151)
at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:844)
at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3156)
at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:625)
at net.minecraft.world.entity.monster.EntityMonster.movementTick(EntityMonster.java:43)
at net.minecraft.world.entity.monster.EntitySkeletonAbstract.movementTick(EntitySkeletonAbstract.java:130)
at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2882)
at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:393)
at net.minecraft.world.entity.monster.EntitySkeleton.tick(EntitySkeleton.java:65)
at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1114)
at net.minecraft.world.level.World.a(World.java:986)
at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:775)
at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by LazoYoung** [comment]
Sir you're asking me why MythicMobs plugin is spamming that error but it seems to have nothing to do with my plugin. Otherwise you might have to submit your game script and the installed version of CraftGames as well in order for me to see the picture to seek the problem.

**Comment by LazoYoung** [comment]
I'm closing this thread as I got no reply for weeks. If you need further assist, you may open up another issue.
