### ISSUE TITLE
Lots of NullPointerExceptions caused by "getType()"

### ISSUE THREAD

**Issue by marcelschoen** [LazoYoung/CraftGames#95]
I'm running a 1.17.1 paper server, and I get tons and tons of these exceptions in the console:
```
0.10 00:23:53 [Server] ERROR Could not pass event ChunkUnloadEvent to MythicMobs v4.13.0-20ae5835
10.10 00:23:53 [Server] INFO java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.mobs.MythicMob.getDespawnMode()" because the return value of "io.lumine.xikage.mythicmobs.mobs.ActiveMob.getType()" is null
10.10 00:23:53 [Server] INFO at io.lumine.xikage.mythicmobs.adapters.bukkit.listeners.ChunkListeners.ChunkUnloadedEvent(ChunkListeners.java:89) ~[MythicMobs-4.13.0.jar:?]
10.10 00:23:53 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor493.execute(Unknown Source) ~[?:?]
10.10 00:23:53 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.world.level.chunk.Chunk.unloadCallback(Chunk.java:988) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$10(PlayerChunk.java:677) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:182) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:687) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.ChunkMapDistance.a(ChunkMapDistance.java:215) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:846) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:929) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:731) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-279]
10.10 00:23:53 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
10.10 00:25:26 [Server] INFO CONSOLE issued server command: /list 
```

I tried MythicMobs 4.13.0 (Premium), 4.13.1 and the latest 5.x snapshot; always the same issue. I have many other plugins too, so I will conduct further tests to see if maybe this relates to another plugin; but judging by the stacktrace, it doesn't look that way. 

Some server startup information from the log:

```
0.10 00:29:39 [Server] INFO Status: Image is up to date for dockerapex/centos7-java:latest
10.10 00:29:39 [Server] INFO WARNING: Published ports are discarded when using host network mode
10.10 00:29:39 [Server] INFO bde2dc7819f8f64603d90cbc9963185d0e4f203d147fbabeac18442ccc57690d
10.10 00:29:41 [Server] INFO System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Linux 4.18.0-305.10.2.el8_4.x86_64 (amd64)
10.10 00:29:41 [Server] INFO Loading libraries, please wait...
10.10 00:29:41 [Server] INFO 2021-10-09 22:29:41,273 main WARN Advanced terminal features are not available in this environment
10.10 00:29:44 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
10.10 00:29:45 [Server] INFO Reloading ResourceManager: Default, bukkit
10.10 00:29:45 [Server] INFO Loaded 7 recipes
10.10 00:29:46 [Server] INFO Starting minecraft server version 1.17.1
10.10 00:29:46 [Server] INFO Loading properties
10.10 00:29:47 [Server] INFO This server is running Paper version git-Paper-279 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6de48db)
10.10 00:29:47 [Server] INFO Server Ping Player Sample Count: 12
10.10 00:29:47 [Server] INFO Using 4 threads for Netty based IO
10.10 00:29:47 [Server] WARN You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
10.10 00:29:47 [Server] INFO Default game type: SURVIVAL
10.10 00:29:47 [Server] INFO Generating keypair
10.10 00:29:47 [Server] INFO Starting Minecraft server on 51.195.60.57:25576
10.10 00:29:47 [Server] INFO Using epoll channel type
10.10 00:29:47 [Server] INFO Paper: Using libdeflate (Linux x86_64) compression from Velocity.
10.10 00:29:47 [Server] INFO Paper: Using OpenSSL 1.0.x (Linux x86_64) cipher from Velocity.
```

**Comment by marcelschoen** [comment]
Somehow I posted this in the completely wrong project... sorry about that... :)
